# Generated by Django 4.1.7 on 2026-02-06 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pln',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm', models.CharField(max_length=270)),
                ('hw', models.TextField()),
                ('tr', models.CharField(choices=[('g', 'Green'), ('y', 'Yellow'), ('r', 'Red')], max_length=35)),
                ('mn', models.IntegerField()),
                ('fz', models.CharField(max_length=45)),
                ('gr', models.TextField(blank=True)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('lks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HSFitKid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gr', models.CharField(max_length=35)),
                ('tgt', models.TextField(blank=True)),
                ('pts', models.IntegerField(default=0)),
                ('str_k', models.IntegerField(default=0)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('bdg', models.JSONField(blank=True, default=list)),
                ('mul', models.FloatField(default=1.0)),
                ('u', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hsfk', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm', models.CharField(max_length=155, unique=True)),
                ('slog', models.TextField(blank=True)),
                ('pts', models.IntegerField(default=0)),
                ('ws', models.IntegerField(default=0)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('col', models.CharField(default='#9B59B6', max_length=7)),
                ('ldr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ldr_grps', to='fitness.hsfitkid')),
                ('mbs', models.ManyToManyField(related_name='grps', to='fitness.hsfitkid')),
            ],
        ),
        migrations.CreateModel(
            name='Drl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knd', models.CharField(choices=[('rn', 'Run'), ('lf', 'Lift'), ('sw', 'Swim'), ('bk', 'Bike'), ('cd', 'Cardio'), ('sp', 'Sport')], max_length=45)),
                ('tm', models.IntegerField()),
                ('eff', models.IntegerField(default=5)),
                ('pts', models.IntegerField(default=0)),
                ('nt', models.TextField(blank=True)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('wx', models.CharField(default='sun', max_length=25)),
                ('k', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drls', to='fitness.hsfitkid')),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
    ]
